// Code generated by Slice Machine. DO NOT EDIT.

import CollectionList from "./CollectionList/index.svelte";
import Hero from "./Hero/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";

export const components = {
  collection_list: CollectionList,
  hero: Hero,
  media_text: MediaText,
  rich_text: RichText,
  section_grid: SectionGrid,
};
