// Code generated by Slice Machine. DO NOT EDIT.

import CollectionList from "./CollectionList/index.svelte";
import Gallery from "./Gallery/index.svelte";
import GridBand from "./GridBand/index.svelte";
import Hero from "./Hero/index.svelte";
import MediaFull from "./MediaFull/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import SplitFeature from "./SplitFeature/index.svelte";
import TitleBand from "./TitleBand/index.svelte";

export const components = {
  collection_list: CollectionList,
  gallery: Gallery,
  grid_band: GridBand,
  hero: Hero,
  media_full: MediaFull,
  media_text: MediaText,
  rich_text: RichText,
  section_grid: SectionGrid,
  split_feature: SplitFeature,
  title_band: TitleBand,
};
